/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viar_core_CameraProcessor */

#ifndef _Included_org_viar_core_CameraProcessor
#define _Included_org_viar_core_CameraProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viar_core_CameraProcessor
 * Method:    processFrame
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_org_viar_core_CameraProcessor_init
  (JNIEnv *, jobject, jint);

JNIEXPORT jobjectArray JNICALL Java_org_viar_core_CameraProcessor_processFrame
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
